In [1]:
import numpy as np

In [3]:
a = np.round(0.5)
print(a)
b = np.round(1.5)
print(b)

0.0
2.0


In [12]:
c = [1,2,3]
c.reverse()
print(c)

[3, 2, 1]


In [13]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
b = np.ones((10,10))
b[:,[0, -1]]=0
b[[0, -1],:]=0
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [49]:
a = np.random.rand(10)
print('a = ', a)
for i in range(10):
    if a[i] >= 0.2 and a[i] <= 0.7:
        a[i] += 10

print('a = ', a)


a =  [0.8024121  0.96100716 0.98181425 0.16630791 0.784605   0.80949175
 0.42572578 0.49391145 0.2549854  0.67530363]
a =  [ 0.8024121   0.96100716  0.98181425  0.16630791  0.784605    0.80949175
 10.42572578 10.49391145 10.2549854  10.67530363]


In [52]:
a = np.array([-3.3, -2.5, -1.5, -0.75, -0.5, 0.5, 0.75, 1.5, 2.5, 3])
a1 = np.round(a)  # [-3. -2. -2. -1. -0.  0.  1.  2.  2.  3.]
a2 = np.ceil(a)  # [-3. -2. -1. -0. -0.  1.  1.  2.  3.  3.]
a3 = np.floor(a)  # [-4. -3. -2. -1. -1.  0.  0.  1.  2.  3.]
a4 = np.trunc(a)  # [-3. -2. -1. -0. -0.  0.  0.  1.  2.  3.]
print(a)
print(a1)
print(a2)
print(a3)
print(a4)

[-3.3  -2.5  -1.5  -0.75 -0.5   0.5   0.75  1.5   2.5   3.  ]
[-3. -2. -2. -1. -0.  0.  1.  2.  2.  3.]
[-3. -2. -1. -0. -0.  1.  1.  2.  3.  3.]
[-4. -3. -2. -1. -1.  0.  0.  1.  2.  3.]
[-3. -2. -1. -0. -0.  0.  0.  1.  2.  3.]


In [60]:
x = 10*np.random.rand(4,4)
oo = np.ones((4,4))
s2c2 = np.square(np.sin(x))+np.square(np.cos(x))
np.equal(oo,s2c2)
np.allclose(oo,s2c2)
print(x)

[[7.32081303 1.92905363 1.35637665 8.72497438]
 [7.44509494 0.92375022 3.84146088 9.58997745]
 [5.0607218  4.94813637 7.97516268 8.85402737]
 [4.69241032 3.46128887 5.75416594 3.89217725]]


In [67]:
x = np.random.randint(1,10,10)
x.sort()
print(x)

[2 3 3 4 5 5 6 6 7 8]


In [69]:
np.argsort(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
z = np.zeros((4,4))
o = np.ones((4,4))
np.concatenate((z,o))
np.concatenate((z,o),axis=1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])