Cho hai ma trận sau:

Ma trận A = [[1,3,4], [2,2,6], [3,2,1]]

Ma trận B = [[2,5,1], [1,3,4], [3,2,3]]

Sử dụng Numpy để thực hiện các phép tính sau:
1. Tính định thức của hai ma trận A và B
2. Tính ma trận nghịch đảo của hai ma trận A và B
3. Tính hạng của hai ma trận A và B
4. Tính hiệu, tổng, tích của hai ma trận A và B
5. Tìm ma trận chuyển vị của hai ma trận A và B




In [13]:
import numpy as np # Khai bao thu vien numpy
X = np.array([[1,3,4,2,1], [2,2,6,1,5], [3,2,1,6,8], [1,2,3,4,5], [9,8,7,6,5]]) # Khởi tạo ma trận A
B = np.array([[2,5,1], [1,3,4], [3,2,3]]) # Khởi tạo ma trận B
A = np.array([[1,4,2], [1,6,9], [9,5,1]])

# In ra ma trận A và B
print('A = [')
for row in A:
    print("  [" + " ".join(f"{val:2}" for val in row) + "]")
print(']')

print('B = [')
for row in B:
    print("  [" + " ".join(f"{val:2}" for val in row) + "]")
print(']')

A = [
  [ 1  4  2]
  [ 1  6  9]
  [ 9  5  1]
]
B = [
  [ 2  5  1]
  [ 1  3  4]
  [ 3  2  3]
]


*Tính định thức của hai ma trận A và B*

In [14]:
Det_A = np.linalg.det(A) # Tính định thức của ma trận A
Det_B = np.linalg.det(B) # Tính định thức của ma trận B
Det_X = np.linalg.det(X) # Tính định thức của ma trận X
print(f'Det(A) = {Det_A:.2f}') # In ra định thức của ma trận A
print(f'Det(B) = {Det_B:.2f}') # In ra định thức của ma trận B
print(f'Det(X) = {Det_X:.2f}') # In ra định thức của ma trận X

Det(A) = 183.00
Det(B) = 40.00
Det(X) = -150.00


Tính ma trận nghịch đảo của hai ma trận A và B

In [15]:
A_inv = np.linalg.inv(A) # Tính ma trận nghịch đảo của ma trận A
B_inv = np.linalg.inv(B) # Tính ma trận nghịch đảo của ma trận B

print('A^(-1) = [') # In ra ma trận nghịch đảo của ma trận A
for row in A_inv:
    print("  [" + " ".join(f"{val:2.2f}" for val in row) + "]")
print(']')

print('B^(-1) = [') # In ra ma trận nghịch đảo của ma trận B
for row in B_inv:
    print("  [" + " ".join(f"{val:2.2f}" for val in row) + "]")
print(']')

A^(-1) = [
  [-0.21 0.03 0.13]
  [0.44 -0.09 -0.04]
  [-0.27 0.17 0.01]
]
B^(-1) = [
  [0.03 -0.33 0.42]
  [0.22 0.07 -0.17]
  [-0.18 0.28 0.02]
]


Tính hạng của hai ma trận A và B

In [16]:
Rank_A = np.linalg.matrix_rank(A) # Tính hạng của ma trận A
Rank_B = np.linalg.matrix_rank(B) # Tính hạng của ma trận B
print(f'Rank(A) = {Rank_A}') # In ra hạng của ma trận A
print(f'Rank(B) = {Rank_B}') # In ra hạng của ma trận B

Rank(A) = 3
Rank(B) = 3


Tính hiệu, tổng, tích của hai ma trận A và B

In [17]:
AddAB = A + B # Tính tổng của hai ma trận A và B
SubAB = A - B # Tính hiệu của hai ma trận A và B
MulAB = A @ B # Tính tích của hai ma trận A và B

print('A + B = [') # In ra tổng của hai ma trận A và B
for row in AddAB:
    print("  [" + " ".join(f"{val:2}" for val in row) + "]")
print(']')

print('A - B = [') # In ra hiệu của hai ma trận A và B
for row in SubAB:
    print("  [" + " ".join(f"{val:2}" for val in row) + "]")
print(']')

print('A * B = [') # In ra tích của hai ma trận A và B
for row in MulAB:
    print("  [" + " ".join(f"{val:2}" for val in row) + "]")
print(']')

A + B = [
  [ 3  9  3]
  [ 2  9 13]
  [12  7  4]
]
A - B = [
  [-1 -1  1]
  [ 0  3  5]
  [ 6  3 -2]
]
A * B = [
  [12 21 23]
  [35 41 52]
  [26 62 32]
]


Tìm ma trận chuyển vị của hai ma trận A và B

In [18]:
A_T = A.T # Tính ma trận chuyển vị của ma trận A
B_T = B.T # Tính ma trận chuyển vị của ma trận B

print('A^T = [') # In ra ma trận chuyển vị của ma trận A
for row in A_T:
    print("  [" + " ".join(f"{val:2}" for val in row) + "]")
print(']')

print('B^T = [') # In ra ma trận chuyển vị của ma trận B
for row in B_T:
    print("  [" + " ".join(f"{val:2}" for val in row) + "]")
print(']')

A^T = [
  [ 1  1  9]
  [ 4  6  5]
  [ 2  9  1]
]
B^T = [
  [ 2  1  3]
  [ 5  3  2]
  [ 1  4  3]
]
