1. Using Numpy to calculate the determined of matrix

In [5]:
import numpy as np 
from scipy import integrate

# Tạo ma trận A
A = np.array([[1,4,2], [1,6,9], [9,5,1]])

# In ra ma trận A và B
print('A = [')
for row in A:
    print("  [" + " ".join(f"{val:2}" for val in row) + "]")
print(']')

Det_A = np.linalg.det(A) # Tính định thức của ma trận A
print(f'Det(A) = {Det_A:.2f}') # In ra định thức của ma trận A

A = [
  [ 1  4  2]
  [ 1  6  9]
  [ 9  5  1]
]
Det(A) = 183.00


2. Create a 2 Dimension array with zeros on the borders and one inside

In [6]:
b = np.ones((10,10))
b[:,[0, -1]]=0
b[[0, -1],:]=0
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


3. Transpose a 2 Dimension matrix by resevsing it

In [7]:
A_T = A.T # Tính ma trận chuyển vị của ma trận A

print('A^T = [') # In ra ma trận chuyển vị của ma trận A
for row in A_T:
    print("  [" + " ".join(f"{val:2}" for val in row) + "]")
print(']')

A^T = [
  [ 1  1  9]
  [ 4  6  5]
  [ 2  9  1]
]


4. Using Scipy package to calculate intergration

In [8]:
def myfunction(x):
    # you need to define result
    result = x**3
    return result

integral = integrate.quad(myfunction, 0, 8) # quad là hàm cho phép tính chạy từ a đến b
print(integral)

(1024.0, 1.1368683772161603e-11)
